import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useAppSelector, useAppDispatch } from "../state/storeHooks";
import { themeActions } from "../state";

const Home: NextPage = () => {
  const theme = useAppSelector((state) => state.theme);

  const dispatch = useAppDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>hi</h1>

      <br />
      <h1>theme: {theme}</h1>
      <button onClick={() => dispatch(themeActions.toLight())}>
        theme light
      </button>
      <button onClick={() => dispatch(themeActions.toDark())}>
        theme dark
      </button>
    </div>
  );
};

export default Home;
